import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { LANGUAGES } from '../src/config.js';

describe('GitHub Pages instructions', () => {
  it('links every localized guide and documents every command', () => {
    const commands = ['/goal', '/status', '/schedule', '/settings', '/help'];
    for (const language of LANGUAGES) {
      const page = readFileSync(`docs/${language}/index.md`, 'utf8');
      expect(page).toContain('https://t.me/my_weight_goal_bot');
      expect(page).toContain(`lang: ${language}`);
      expect(page).toMatch(/^description: .+$/mu);
      if (language !== 'en') {
        expect(page).not.toContain('description: Instructions and commands for the multilingual Telegram weight-goal bot');
      }
      for (const command of commands) expect(page).toContain(command);
      for (const linkedLanguage of LANGUAGES) expect(page).toContain(`../${linkedLanguage}/`);
    }
  });

  it('localizes the GitHub Pages theme chrome for every guide', () => {
    const layout = readFileSync('docs/_layouts/default.html', 'utf8');
    const ui = readFileSync('docs/_data/ui.yml', 'utf8');

    expect(layout).toContain('site.data.ui[page.lang]');
    expect(layout).toContain('{{ ui.skip }}');
    expect(layout).toContain('{{ ui.view_github }}');
    expect(layout).not.toContain('>View on GitHub<');
    expect(layout).not.toContain('This page was generated by');
    for (const language of LANGUAGES) {
      expect(ui).toMatch(new RegExp(`^${language}:$`, 'mu'));
    }
  });

  it('offers all languages from the landing page', () => {
    const landing = readFileSync('docs/index.md', 'utf8');
    for (const language of LANGUAGES) expect(landing).toContain(`./${language}/`);
  });
});
