import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { LANGUAGES } from '../src/config.js';

describe('GitHub Pages instructions', () => {
  it('links every localized guide and documents every command', () => {
    const commands = ['/goal', '/status', '/schedule', '/settings', '/help'];
    for (const language of LANGUAGES) {
      const page = readFileSync(`docs/${language}/index.md`, 'utf8');
      expect(page).toContain('https://t.me/my_weight_goal_bot');
      expect(page).toContain(`lang: ${language}`);
      expect(page).toMatch(/^description: .+$/mu);
      expect(page.match(/^description: (.+)$/mu)?.[1]).not.toMatch(/multilingual|многоязыч|multiling|mehrsprach|多语言|多言語|multibahasa/iu);
      for (const command of commands) expect(page).toContain(command);
      expect(page.match(/\/settings/gu)?.length).toBeGreaterThanOrEqual(2);
      for (const linkedLanguage of LANGUAGES) expect(page).toContain(`../${linkedLanguage}/`);
    }
  });

  it('localizes the GitHub Pages theme chrome for every guide', () => {
    const layout = readFileSync('docs/_layouts/default.html', 'utf8');
    const ui = readFileSync('docs/_data/ui.yml', 'utf8');

    expect(layout).toContain('site.data.ui[page.lang]');
    expect(layout).toContain('{{ ui.skip }}');
    expect(layout).toContain('{{ ui.view_github }}');
    expect(layout).not.toContain('>View on GitHub<');
    expect(layout).not.toContain('This page was generated by');
    for (const language of LANGUAGES) {
      expect(ui).toMatch(new RegExp(`^${language}:$`, 'mu'));
    }
  });

  it('keeps commands and language settings out of user-benefit introductions', () => {
    const benefitWords = {
      ru: ['Фото', 'напоминает', 'достижения'], en: ['Photo', 'reminders', 'achievements'],
      zh: ['照片', '提醒', '成就'], es: ['foto', 'recordatorios', 'logro'], pt: ['foto', 'lembretes', 'conquista'],
      de: ['Foto', 'erinnert', 'Erfolge'], fr: ['photo', 'rappels', 'succès'],
      ja: ['写真', 'リマインダー', '実績'], id: ['foto', 'pengingat', 'pencapaian'],
    } as const;
    const settingsCopy = /\/(?:goal|status|schedule|settings|help)|commands?|команд|命令|comandos?|Befehle|commandes|コマンド|perintah|languages?|язык|语言|idioma|Sprache|langue|言語|bahasa/iu;

    for (const language of LANGUAGES) {
      const page = readFileSync(`docs/${language}/index.md`, 'utf8');
      const description = page.match(/^description: (.+)$/mu)?.[1] ?? '';
      const introduction = page.slice(page.indexOf('\n# '), page.indexOf('\n## '));
      expect(description).not.toMatch(settingsCopy);
      expect(introduction).not.toMatch(settingsCopy);
      for (const word of benefitWords[language]) expect(introduction).toContain(word);
    }
  });

  it('offers all languages from the landing page', () => {
    const landing = readFileSync('docs/index.md', 'utf8');
    for (const language of LANGUAGES) expect(landing).toContain(`./${language}/`);
  });
});
